_TEXT = '''
        
        HACKWARE STRIKE FORCE
        ----------------------------------------------------------
        Seus arquivos foram criptografados 
        

MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0OxxdddxkO0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXko:,.......... ;cd0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd;.................. :oOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXd;........................,oKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx;....,:lodxxxxxkkkxxdol:,.... dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXo...;ok0KXXXXXXXXXXXXXKKKK0xo;...dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd..:x0XXXXXXXXNXXXXXXXXXXKKK00Od:. kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;.o0XXXXXNXXNNNNXXXXXXXXKKKKK00Okc.:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd lKXXXXXXNNNNNNNNXXXXXXXXKKK000Okx; xWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl;OXXXXXXXXXNNNNNNNXXXXXXKKKKKK00Oko,lNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXcc0KXXXXXXXXXNWWWNNNNNXXKKKKKKK00Oxd;:KMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;cKXXXXXXXXXNNNWNXXXNNNXKKKKKKKKKOxd, OMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk ckdooxOXNXXXXNWNXKKXNNXKKXXXKxc;,;: .kMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx. ,.  ..:xKNXXNNNXKKXNXKKXNKx;.    ...dWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo....     .,dKNXNXXKKXNXKNNO:.    .... lNMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc. ,.       .lKNNXKKKXNXXNO;      .... :XMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;.cc.        .dXXXXK0XXXX0:        .,:.;KMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0:ckd;.         kKKK0OKKK0c.       . ;olc0MMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0d0Kko:,.....   .lkOOO0Od;.  ..... ;,:kOokWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKOKXXKkxddol:,....o0KXKk:....,:cooddxO0kcdWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxOKKXXXKKK0kxdoldxxoccloolloxO0000K0Oxl lWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK::xOOkddkO0KKKKK0c..  .lkOOOkkxxdxkxdc. cNMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0, . ,,..,oOK000Kx   ,:.,dkkkkko,. ; .   ;XMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0     .    d0KKKKOdldkkxdxkkkko.  ..      0MMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNx.      . .l0KXXXKK0K0O0K0OOkd,  .        cXMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMM0:.      ....l0KKKKKXXXKKKXKOOxd, ..        .lNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNc         ,;.c0KKKKKXXK0KKK00Oxl..,.         .dWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWX0o.         .lxxO000OxkOxxkxkxxko:;:.           .dNMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWNKOdl: ..            dOkOOOOkOOkkkxkkkxlcc              .d0KNWMMMMMMWWMMMMMMMMMM
MMMMMMMMMMMMMMMWX0xc;..                  ,xO0OOOkkOOOkkkxxdoc                ...,;cldk0XWWMMMMMMMMMM
MMMMMMMMMMMN0xl; .                        ,kKKK0O000OOOOO0Od,                         . ;lxKWMMMMMMM
MMMMMMMMNkl;.                              :OKKKKKKK0000K0Ol.                              .cONWMMMM
MMMMMMMNo.                                   coooooooloool;.                                 ;0WMMMM
MMMMMMMW0l.                                                                               . dXWMMMMM
MMMMMMMMMWKl                                                                            .;xXWWMMMMMM
MMMMMMMMMMMWXd,.                                                                     . l0WMMMMMMMMMM
MMMMMMMMMMMMMMNkc.                                                                .,lONWMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWKd:.                                                           :d0NWMMWMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWWWKd: .                                                  .;oOXWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWXOdc,..                                        .,:okXWMWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWWX0Oxxdddooooooooolllllllc:;,,....... ,:cokKNWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNXKKKKXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

        '''